### ISSUE TITLE
KeyError 'mm39_ref'

### ISSUE THREAD

**Issue by sandain** [ylab-hi/ScanNeo#11]
While testing ScanNeo on some mouse data, I get the following error.  I have a patch that I will submit shortly that fixes this issue.

```
$ ScanNeo.py indel -i ../variant_calling_work/CRO030321_001.noDups.bam -r mm39
Checking for 'picard': found /mnt/store3/clustcrilab/tools/scanneo/miniconda/bin/picard

Checking for 'vep': found /mnt/store3/clustcrilab/tools/scanneo/miniconda/bin/vep

Checking for 'sambamba': found /mnt/store3/clustcrilab/tools/scanneo/miniconda/bin/sambamba

Checking for 'bedtools': found /mnt/store3/clustcrilab/tools/scanneo/miniconda/bin/bedtools

Checking for 'bwa': found /mnt/store3/clustcrilab/tools/scanneo/miniconda/bin/bwa

Checking for 'transIndel_build_RNA.py': found /mnt/store3/clustcrilab/tools/scanneo/bin/transIndel_build_RNA.py

Checking for 'transIndel_call.py': found /mnt/store3/clustcrilab/tools/scanneo/bin/transIndel_call.py

Traceback (most recent call last):
  File "/mnt/store3/clustcrilab/tools/scanneo/bin/ScanNeo.py", line 987, in <module>
    main()
  File "/mnt/store3/clustcrilab/tools/scanneo/bin/ScanNeo.py", line 899, in main
    bwa_bam = preprocessing(args.input, ref=args.ref)
  File "/mnt/store3/clustcrilab/tools/scanneo/bin/ScanNeo.py", line 163, in preprocessing
    fasta = config["mm39_ref"]
KeyError: 'mm39_ref'
```

**Comment by dolittle007** [comment]
Thanks a lot.

**Comment by sandain** [comment]
No problem. Thanks for starting the work on adding mouse support
