### ISSUE TITLE
Errors about parsing the VEP annotation output file (tmp_vcf)

### ISSUE THREAD

**Issue by paulhtyang** [ylab-hi/ScanNeo#21]
I am running the latest version (v2.2) of ScanNeo and VEP (v106.1), and successfully complete the first step. However, I got some error messages by running the second step of the workflow below:
Thanks,
Paul

Command:
ScanNeo.py anno --dir /data/ensemble -i Adipose01_R1.HISAT2-2.1.0.aligned.sorted.indel.vcf -o Adipose01_R1.HISAT2-2.1.0.aligned.sorted.indel.vcf.ann

Error messages:
---------------------------------------------------------------------------------------------------------------------------
Checking for 'picard': found /data/anaconda3/envs/Ensembl/bin/picard

Checking for 'vep': found /data/anaconda3/envs/Ensembl/bin/vep

Checking for 'sambamba': found /data/anaconda3/envs/Ensembl/bin/sambamba

Checking for 'bedtools': found /data/anaconda3/envs/Ensembl/bin/bedtools

Checking for 'bwa': found /data/anaconda3/envs/Ensembl/bin/bwa

Checking for 'transIndel_build_RNA.py': found /data/tools/transIndel/transIndel_build_RNA.py

Checking for 'transIndel_call.py': found /data/tools/transIndel/transIndel_call.py

Begin deal with VCF: Adipose01_R1.HISAT2-2.1.0.aligned.sorted.indel.vcf
VCF add sequences [ref, alt] accomplished!
vep --offline --force_overwrite --dir /data/ensemble --species homo_sapiens --assembly GRCh38 --input_file pre_vep.7219.vcf --format vcf
--output_file tmp.953900885997.vcf         --vcf --symbol --terms SO --af --af_gnomad --plugin Downstream --plugin Wildtype --no_stats
VEP begin annotation
 VEP annotation finished!
VEP accomplished!
Traceback (most recent call last):
  File "/data/tools/ScanNeo/ScanNeo.py", line 1011, in <module>
    main()
  File "/data/tools/ScanNeo/ScanNeo.py", line 930, in main
    cutoff=args.cutoff,
  File "/data/tools/ScanNeo/ScanNeo.py", line 376, in vep_caller
    csq_allele = alleles_dict[alt]
TypeError: unhashable type: '_Substitution'
--------------------------------------------------------------------------------------------------------------------------------

**Comment by sandain** [comment]
I believe I have fixed this issue. Check out PR #19 and issue #18 for more information.

**Comment by paulhtyang** [comment]
Thank you, Sandian,

I did updates the codes at the lines (ssue https://github.com/ylab-hi/ScanNeo/issues/18) you showed for ScanNeo.py file. Now it is working very well.
Paul
